import assert from 'node:assert/strict';
import { readFileSync, statSync } from 'node:fs';
import test from 'node:test';

const root = new URL('../..', import.meta.url);
const sourceCss = readFileSync(new URL('themes/fancontrol-classic/theme.css', root), 'utf8');
const exportedCss = readFileSync(new URL('exported-themes/fancontrol-classic/theme.css', root), 'utf8');
const dockTextureSource = readFileSync(new URL('themes/fancontrol-classic/assets/patterns/circuit-board.svg', root), 'utf8');
const dockTextureExport = readFileSync(new URL('exported-themes/fancontrol-classic/assets/patterns/circuit-board.svg', root), 'utf8');
const deviceStatusSource = readFileSync(new URL('frontend/src/app/components/DeviceStatus.tsx', root), 'utf8');
const globalsCss = readFileSync(new URL('frontend/src/app/globals.css', root), 'utf8');
const manifest = JSON.parse(readFileSync(new URL('themes/fancontrol-classic/theme.json', root), 'utf8'));
const advancedCss = sourceCss.slice(sourceCss.indexOf('/* Advanced contract'));

test('FanControl Classic uses the advanced theme contract', () => {
  assert.equal(manifest.id, 'fancontrol-classic');
  assert.equal(manifest.layer, 'advanced');
  assert.equal(manifest.contract, 'fancontrol/v1');
  assert.equal(manifest.version, '2.1.9');
  assert.match(sourceCss, /--classic-curtain:\s*url\("assets\/curtain\.webp"\)/);
  assert.match(sourceCss, /--classic-panel-texture:\s*url\("assets\/patterns\/panel-texture\.svg"\)/);
  assert.doesNotMatch(sourceCss, /assets\/(?:curtain\.svg|panel-texture\.webp)/);
  assert.match(sourceCss, /classic-(?:grid|dock|signal)-texture/);
  assert.match(advancedCss, /\.glacier-shell::before \{[\s\S]*?background: var\(--classic-curtain\)/);
  assert.match(advancedCss, /\.glacier-content-panel::after \{[\s\S]*?content: none !important/);
  assert.doesNotMatch(advancedCss, /\.glacier-shell::before\s*\{[^}]*classic-grid-texture/);
  assert.doesNotMatch(sourceCss, /content:\s*["'](?:AUX|DATA LOG)["']/);
  assert.match(sourceCss, /\.glacier-hero-art,\s*\nhtml\[data-theme="fancontrol-classic"\] \.glacier-hero-art-label/);
  assert.doesNotMatch(deviceStatusSource, /ice-operator-banner/);
  assert.match(sourceCss, /data-theme-ui="sidebar-item"/);
  assert.match(sourceCss, /data-slot="dialog-content"/);
  assert.match(sourceCss, /data-theme-ui="switch"/);
  assert.match(sourceCss, /data-theme-ui="hero-brand-mark"\]\s*\{\s*display: none !important/);
  assert.match(sourceCss, /assets\/patterns\/card-ornament\.svg/);
  assert.match(sourceCss, /rgba\(255, 255, 255, 0\.48\)/);
  assert.match(sourceCss, /rgba\(237, 247, 255, 0\.24\)/);
  assert.match(sourceCss, /--theme-card-backdrop-filter: blur\(12px\) saturate\(120%\)/);
  assert.match(deviceStatusSource, /data-theme-card="connection-empty"/);
  assert.match(globalsCss, /data-theme-card="device-hero"\]::before/);
  assert.match(globalsCss, /data-theme-ui="hero-brand-mark"\]\s*\{/);
  assert.match(globalsCss, /data-theme-card="connection-empty"/);
  assert.doesNotMatch(globalsCss.slice(globalsCss.indexOf('Custom themes share')), /data-theme="dune"/);
  assert.match(advancedCss, /\.glacier-hero-card \{[\s\S]*?min-height: 0 !important/);
  assert.match(advancedCss, /\.glacier-hero-card \[data-theme-ui="hero-brand-mark"\] \{\s*display: none !important/);
  assert.match(advancedCss, /--classic-surface-background:\s*linear-gradient\(145deg, rgba\(255, 255, 255, 0\.12\), rgba\(237, 247, 255, 0\.03\)\)/);
  assert.match(advancedCss, /--classic-surface-filter: blur\(2px\) saturate\(104%\)/);
  assert.match(advancedCss, /--classic-dock-border:\s*rgba\(65, 133, 202, 0\.24\)/);
  assert.match(advancedCss, /--classic-dock-shadow:[\s\S]*?4px 0 16px -14px rgba\(47, 116, 255, 0\.28\)/);
  assert.doesNotMatch(advancedCss, /--classic-dock-shadow:[\s\S]*?0 0 0 1px/);
  assert.match(advancedCss, /\.glacier-sidebar \{[\s\S]*?border-color: transparent !important;[\s\S]*?background: transparent !important;[\s\S]*?box-shadow: none !important/);
  assert.match(advancedCss, /\.glacier-sidebar::before \{[\s\S]*?inset: 0\.55rem 0\.4rem !important;[\s\S]*?border: 1px solid var\(--classic-dock-border\) !important;[\s\S]*?background:\s*(?:var\(--classic-dock-texture\) center top \/ 152px 152px repeat,\s*)+var\(--classic-surface-background\) !important;[\s\S]*?box-shadow: var\(--classic-dock-shadow\) !important;[\s\S]*?animation: classic-dock-drift 32s ease-in-out infinite alternate/);
  assert.match(advancedCss, /\.glacier-sidebar::after \{[\s\S]*?content: none !important;[\s\S]*?display: none !important/);
  assert.match(advancedCss, /data-theme-ui="compatibility-divider"[\s\S]*?border-top: 0 !important/);
  assert.match(advancedCss, /data-theme-page="status"\] :is\([\s\S]*?\.glacier-metric-card,[\s\S]*?\.glacier-control-card,[\s\S]*?data-theme-card="fan-curve-preview"[\s\S]*?data-theme-card="temperature-history"[\s\S]*?background: var\(--classic-surface-background\) !important;[\s\S]*?backdrop-filter: var\(--classic-surface-filter\) !important/);
  assert.match(advancedCss, /glacier-control-card \.glacier-stat-tile,[\s\S]*?glacier-control-card \.backdrop-blur-xl[\s\S]*?background: var\(--classic-surface-background\) !important;[\s\S]*?backdrop-filter: var\(--classic-surface-filter\) !important/);
  assert.match(advancedCss, /glacier-control-card::before \{\s*right: 0\.72rem;\s*transform: none;/);
  assert.match(advancedCss, /--theme-chart-canvas-background:\s*var\(--classic-surface-background\)/);
  assert.match(advancedCss, /classic-dock-texture\) center top \/ 152px 152px repeat/);
  assert.match(advancedCss, /classic-dock-drift 32s ease-in-out infinite alternate/);
  assert.match(sourceCss, /prefers-reduced-motion: reduce[\s\S]*?\.glacier-sidebar::before[\s\S]*?animation: none !important/);
  assert.match(dockTextureSource, /width="304" height="304"/);
  assert.match(dockTextureSource, /<title>Artboard 3 Copy 2<\/title>/);
  assert.match(dockTextureSource, /fill="#7da7df"/);
  assert.match(dockTextureSource, /fill-opacity="0\.04"/);
  assert.equal(dockTextureSource, dockTextureExport);
  assert.match(advancedCss, /\.glacier-hero-actions \{[\s\S]*?background: transparent !important/);
  assert.match(advancedCss, /width: 5\.25rem;\s*height: 1\.4rem/);
  assert.doesNotMatch(sourceCss, /\.glacier-shell\s*>\s*\*\s*\{/);
  assert.match(sourceCss, /\.glacier-sidebar,\s*\nhtml\[data-theme="fancontrol-classic"\] \.glacier-shell > section\s*\{\s*\n\s*position: relative;/);
});

test('FanControl Classic exported CSS stays byte-identical and ships its assets', () => {
  assert.equal(sourceCss, exportedCss);
  const curtain = statSync(new URL('themes/fancontrol-classic/assets/curtain.webp', root));
  const texture = statSync(new URL('themes/fancontrol-classic/assets/patterns/panel-texture.svg', root));
  const ornament = statSync(new URL('themes/fancontrol-classic/assets/patterns/card-ornament.svg', root));
  const exportedCurtain = statSync(new URL('exported-themes/fancontrol-classic/assets/curtain.webp', root));
  const exportedTexture = statSync(new URL('exported-themes/fancontrol-classic/assets/patterns/panel-texture.svg', root));
  const exportedOrnament = statSync(new URL('exported-themes/fancontrol-classic/assets/patterns/card-ornament.svg', root));
  assert.ok(curtain.size < 40_000);
  assert.ok(texture.size < 5_000);
  assert.ok(ornament.size < 5_000);
  assert.equal(exportedCurtain.size, curtain.size);
  assert.equal(exportedTexture.size, texture.size);
  assert.equal(exportedOrnament.size, ornament.size);
});
