// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AutoScanDevices() {
  return window['go']['main']['App']['AutoScanDevices']();
}

export function CancelUpdateDownload(arg1) {
  return window['go']['main']['App']['CancelUpdateDownload'](arg1);
}

export function CheckLatestRelease(arg1) {
  return window['go']['main']['App']['CheckLatestRelease'](arg1);
}

export function CheckWindowsAutoStart() {
  return window['go']['main']['App']['CheckWindowsAutoStart']();
}

export function ConnectDevice() {
  return window['go']['main']['App']['ConnectDevice']();
}

export function ConnectDeviceCandidate(arg1) {
  return window['go']['main']['App']['ConnectDeviceCandidate'](arg1);
}

export function ConnectNativeDevice(arg1) {
  return window['go']['main']['App']['ConnectNativeDevice'](arg1);
}

export function ControlWiFiScan(arg1) {
  return window['go']['main']['App']['ControlWiFiScan'](arg1);
}

export function DeleteDeviceProfile(arg1) {
  return window['go']['main']['App']['DeleteDeviceProfile'](arg1);
}

export function DeleteFanCurveProfile(arg1) {
  return window['go']['main']['App']['DeleteFanCurveProfile'](arg1);
}

export function DisconnectDevice() {
  return window['go']['main']['App']['DisconnectDevice']();
}

export function DownloadAndInstallUpdate(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['DownloadAndInstallUpdate'](arg1, arg2, arg3, arg4, arg5);
}

export function ExportDeviceProfiles() {
  return window['go']['main']['App']['ExportDeviceProfiles']();
}

export function ExportDeviceProfilesToFile() {
  return window['go']['main']['App']['ExportDeviceProfilesToFile']();
}

export function ExportDiagnosticsToFile() {
  return window['go']['main']['App']['ExportDiagnosticsToFile']();
}

export function ExportFanCurveProfiles() {
  return window['go']['main']['App']['ExportFanCurveProfiles']();
}

export function ExportFanCurveProfilesToFile() {
  return window['go']['main']['App']['ExportFanCurveProfilesToFile']();
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetAutoStartMethod() {
  return window['go']['main']['App']['GetAutoStartMethod']();
}

export function GetAvailableGears() {
  return window['go']['main']['App']['GetAvailableGears']();
}

export function GetBridgeProgramStatus() {
  return window['go']['main']['App']['GetBridgeProgramStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetCurrentFanData() {
  return window['go']['main']['App']['GetCurrentFanData']();
}

export function GetDebugInfo() {
  return window['go']['main']['App']['GetDebugInfo']();
}

export function GetDeviceDebugFrames() {
  return window['go']['main']['App']['GetDeviceDebugFrames']();
}

export function GetDeviceProfiles() {
  return window['go']['main']['App']['GetDeviceProfiles']();
}

export function GetDeviceStatus() {
  return window['go']['main']['App']['GetDeviceStatus']();
}

export function GetFanCurve() {
  return window['go']['main']['App']['GetFanCurve']();
}

export function GetFanCurveProfiles() {
  return window['go']['main']['App']['GetFanCurveProfiles']();
}

export function GetSupportedDeviceProfiles() {
  return window['go']['main']['App']['GetSupportedDeviceProfiles']();
}

export function GetTemperature() {
  return window['go']['main']['App']['GetTemperature']();
}

export function GetTemperatureHistory() {
  return window['go']['main']['App']['GetTemperatureHistory']();
}

export function GetThemeCSS(arg1) {
  return window['go']['main']['App']['GetThemeCSS'](arg1);
}

export function GetUserDeviceProfiles() {
  return window['go']['main']['App']['GetUserDeviceProfiles']();
}

export function HideWindow() {
  return window['go']['main']['App']['HideWindow']();
}

export function ImportDeviceProfiles(arg1) {
  return window['go']['main']['App']['ImportDeviceProfiles'](arg1);
}

export function ImportFanCurveProfiles(arg1) {
  return window['go']['main']['App']['ImportFanCurveProfiles'](arg1);
}

export function InitSystemTray() {
  return window['go']['main']['App']['InitSystemTray']();
}

export function IsAutoStartLaunch() {
  return window['go']['main']['App']['IsAutoStartLaunch']();
}

export function IsRunningAsAdmin() {
  return window['go']['main']['App']['IsRunningAsAdmin']();
}

export function ListSerialPorts() {
  return window['go']['main']['App']['ListSerialPorts']();
}

export function ListThemes() {
  return window['go']['main']['App']['ListThemes']();
}

export function ManualSetFanSpeed(arg1) {
  return window['go']['main']['App']['ManualSetFanSpeed'](arg1);
}

export function OnWindowClosing(arg1) {
  return window['go']['main']['App']['OnWindowClosing'](arg1);
}

export function OpenThemesFolder() {
  return window['go']['main']['App']['OpenThemesFolder']();
}

export function PauseUpdateDownload() {
  return window['go']['main']['App']['PauseUpdateDownload']();
}

export function ProbeBLEGATT(arg1) {
  return window['go']['main']['App']['ProbeBLEGATT'](arg1);
}

export function QuitAll() {
  return window['go']['main']['App']['QuitAll']();
}

export function QuitApp() {
  return window['go']['main']['App']['QuitApp']();
}

export function RefreshDeviceSettings() {
  return window['go']['main']['App']['RefreshDeviceSettings']();
}

export function ReinstallPawnIO() {
  return window['go']['main']['App']['ReinstallPawnIO']();
}

export function ResetLearnedOffsets() {
  return window['go']['main']['App']['ResetLearnedOffsets']();
}

export function RestartPawnIO() {
  return window['go']['main']['App']['RestartPawnIO']();
}

export function ResumeUpdateDownload() {
  return window['go']['main']['App']['ResumeUpdateDownload']();
}

export function SaveDeviceProfile(arg1, arg2) {
  return window['go']['main']['App']['SaveDeviceProfile'](arg1, arg2);
}

export function SaveFanCurveProfile(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SaveFanCurveProfile'](arg1, arg2, arg3, arg4);
}

export function ScanBLEDevices(arg1) {
  return window['go']['main']['App']['ScanBLEDevices'](arg1);
}

export function ScanDeviceCandidates(arg1) {
  return window['go']['main']['App']['ScanDeviceCandidates'](arg1);
}

export function ScanWiFiDevices(arg1) {
  return window['go']['main']['App']['ScanWiFiDevices'](arg1);
}

export function SendDeviceDebugCommand(arg1, arg2) {
  return window['go']['main']['App']['SendDeviceDebugCommand'](arg1, arg2);
}

export function SetActiveDeviceProfile(arg1) {
  return window['go']['main']['App']['SetActiveDeviceProfile'](arg1);
}

export function SetActiveFanCurveProfile(arg1) {
  return window['go']['main']['App']['SetActiveFanCurveProfile'](arg1);
}

export function SetAutoControl(arg1) {
  return window['go']['main']['App']['SetAutoControl'](arg1);
}

export function SetAutoStartWithMethod(arg1, arg2) {
  return window['go']['main']['App']['SetAutoStartWithMethod'](arg1, arg2);
}

export function SetBrightness(arg1) {
  return window['go']['main']['App']['SetBrightness'](arg1);
}

export function SetCustomSpeed(arg1, arg2) {
  return window['go']['main']['App']['SetCustomSpeed'](arg1, arg2);
}

export function SetDebugMode(arg1) {
  return window['go']['main']['App']['SetDebugMode'](arg1);
}

export function SetFanCurve(arg1) {
  return window['go']['main']['App']['SetFanCurve'](arg1);
}

export function SetGearLight(arg1) {
  return window['go']['main']['App']['SetGearLight'](arg1);
}

export function SetLightStrip(arg1) {
  return window['go']['main']['App']['SetLightStrip'](arg1);
}

export function SetManualGear(arg1, arg2) {
  return window['go']['main']['App']['SetManualGear'](arg1, arg2);
}

export function SetPowerOnStart(arg1) {
  return window['go']['main']['App']['SetPowerOnStart'](arg1);
}

export function SetSmartStartStop(arg1) {
  return window['go']['main']['App']['SetSmartStartStop'](arg1);
}

export function SetTemperatureHistoryEnabled(arg1) {
  return window['go']['main']['App']['SetTemperatureHistoryEnabled'](arg1);
}

export function SetWiFiSmartStartStopStandbySpeed(arg1) {
  return window['go']['main']['App']['SetWiFiSmartStartStopStandbySpeed'](arg1);
}

export function SetWindowsAutoStart(arg1) {
  return window['go']['main']['App']['SetWindowsAutoStart'](arg1);
}

export function ShowWindow() {
  return window['go']['main']['App']['ShowWindow']();
}

export function Startup(arg1) {
  return window['go']['main']['App']['Startup'](arg1);
}

export function TestBridgeProgram() {
  return window['go']['main']['App']['TestBridgeProgram']();
}

export function TestDeviceProfile(arg1) {
  return window['go']['main']['App']['TestDeviceProfile'](arg1);
}

export function TestTemperatureReading() {
  return window['go']['main']['App']['TestTemperatureReading']();
}

export function UpdateCompletedOnLaunch() {
  return window['go']['main']['App']['UpdateCompletedOnLaunch']();
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateGuiResponseTime() {
  return window['go']['main']['App']['UpdateGuiResponseTime']();
}

export function WindowBlurEnabled() {
  return window['go']['main']['App']['WindowBlurEnabled']();
}
