// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {types} from '../models';
import {guiapp} from '../models';
import {deviceproto} from '../models';
import {theme} from '../models';
import {context} from '../models';
import {ipc} from '../models';

export function AutoScanDevices():Promise<Record<string, any>>;

export function BeginNoiseDiagnostic(arg1:types.NoiseDiagnosticBeginRequest):Promise<types.NoiseDiagnosticSession>;

export function CancelNoiseDiagnostic(arg1:string):Promise<void>;

export function CancelScreenImageTransfer():Promise<boolean>;

export function CancelUpdateDownload(arg1:string):Promise<void>;

export function CheckBlackSharkFirmwareUpdate():Promise<types.BlackSharkFirmwareStatus>;

export function CheckLatestRelease(arg1:string):Promise<guiapp.UpdateRelease>;

export function CheckWindowsAutoStart():Promise<boolean>;

export function ConnectDevice():Promise<boolean>;

export function ConnectDeviceCandidate(arg1:types.DeviceConnectRequest):Promise<boolean>;

export function ConnectNativeDevice(arg1:string):Promise<boolean>;

export function ControlWiFiScan(arg1:string):Promise<boolean>;

export function DeleteDeviceProfile(arg1:string):Promise<void>;

export function DeleteFanCurveProfile(arg1:string):Promise<void>;

export function DeleteScreenHistoryImage(arg1:string):Promise<boolean>;

export function DisconnectDevice():Promise<void>;

export function DownloadAndInstallUpdate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string):Promise<void>;

export function EndNoiseDiagnostic(arg1:string):Promise<void>;

export function ExportBlackSharkConfigSnapshot():Promise<guiapp.ConfigSnapshotExportResult>;

export function ExportDeviceProfiles():Promise<string>;

export function ExportDeviceProfilesToFile():Promise<string>;

export function ExportDiagnosticsToFile():Promise<string>;

export function ExportFanCurveProfiles(arg1:Array<string>):Promise<string>;

export function ExportFanCurveProfilesToFile(arg1:Array<string>):Promise<string>;

export function GetAppVersion():Promise<string>;

export function GetAutoStartMethod():Promise<string>;

export function GetAvailableGears():Promise<Record<string, Array<types.GearCommand>>>;

export function GetBlackSharkCurveTempRange():Promise<types.BlackSharkCurveTempRange>;

export function GetBlackSharkFirmwareStatus():Promise<types.BlackSharkFirmwareStatus>;

export function GetBlackSharkHostEffects():Promise<types.BlackSharkHostEffects>;

export function GetBlackSharkInfo():Promise<types.BlackSharkInfo>;

export function GetBlackSharkLcdDisplay():Promise<guiapp.BlackSharkLcdDisplayPayload>;

export function GetBlackSharkManualGearPresets():Promise<deviceproto.BlackSharkManualGearPresetsPayload>;

export function GetBlackSharkRgbLighting():Promise<types.BlackSharkRgbLighting>;

export function GetBlackSharkRgbLightingCached():Promise<types.BlackSharkRgbLighting>;

export function GetBridgeProgramStatus():Promise<Record<string, any>>;

export function GetConfig():Promise<types.AppConfig>;

export function GetCurrentFanData():Promise<types.FanData>;

export function GetDebugInfo():Promise<Record<string, any>>;

export function GetDeviceDebugFrames():Promise<Array<types.DeviceDebugFrame>>;

export function GetDeviceProfiles():Promise<types.DeviceProfilesPayload>;

export function GetDeviceStatus():Promise<Record<string, any>>;

export function GetFanCurve():Promise<Array<types.FanCurvePoint>>;

export function GetFanCurveProfiles():Promise<types.FanCurveProfilesPayload>;

export function GetSceneRules():Promise<guiapp.SceneRulesPayload>;

export function GetScreenImageCached():Promise<guiapp.ScreenImageReadPayload>;

export function GetScreenImageInfo():Promise<guiapp.ScreenImageInfoPayload>;

export function GetSupportedDeviceProfiles():Promise<Array<types.DeviceProfile>>;

export function GetTemperature():Promise<types.TemperatureData>;

export function GetTemperatureHistory():Promise<types.TemperatureHistoryPayload>;

export function GetThemeCSS(arg1:string):Promise<string>;

export function GetUserDeviceProfiles():Promise<Array<types.DeviceProfile>>;

export function HideWindow():Promise<void>;

export function ImportDeviceProfiles(arg1:string):Promise<void>;

export function ImportFanCurveProfiles(arg1:string):Promise<void>;

export function InitSystemTray():Promise<void>;

export function IsAutoStartLaunch():Promise<boolean>;

export function IsRunningAsAdmin():Promise<boolean>;

export function ListSceneProcesses():Promise<Array<string>>;

export function ListScreenHistoryImages(arg1:number,arg2:number):Promise<guiapp.ScreenHistoryListPayload>;

export function ListScreenPresets():Promise<guiapp.ScreenPresetListPayload>;

export function ListSerialPorts():Promise<Array<types.SerialPortInfo>>;

export function ListThemes():Promise<Array<theme.Meta>>;

export function ManualSetFanSpeed(arg1:number):Promise<boolean>;

export function OnWindowClosing(arg1:context.Context):Promise<boolean>;

export function OpenThemesFolder():Promise<void>;

export function PauseUpdateDownload():Promise<boolean>;

export function PickScreenImageFile():Promise<string>;

export function PreviewScreenImageCrop(arg1:string,arg2:number,arg3:number,arg4:number):Promise<guiapp.ScreenCropPreviewPayload>;

export function ProbeBLEGATT(arg1:types.BLEGATTProbeParams):Promise<types.BLEGATTProbeResult>;

export function QuitAll():Promise<void>;

export function QuitApp():Promise<void>;

export function ReadScreenImageFromDevice():Promise<guiapp.ScreenImageReadPayload>;

export function RefreshDeviceSettings():Promise<types.DeviceSettings>;

export function ReinstallPawnIO():Promise<Record<string, any>>;

export function ReportClientIssue(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ResetBlackSharkCooling():Promise<boolean>;

export function ResetBlackSharkRgb():Promise<boolean>;

export function ResetLearnedOffsets():Promise<void>;

export function RestartCore(arg1:boolean):Promise<void>;

export function RestartPawnIO():Promise<types.BridgeTemperatureData>;

export function RestoreBlackSharkConfigFromFile():Promise<types.BlackSharkConfigRestoreResult>;

export function ResumeUpdateDownload():Promise<boolean>;

export function SaveAxisNoiseProfile(arg1:types.AxisNoiseProfile):Promise<types.AxisNoiseProfile>;

export function SaveDeviceProfile(arg1:types.DeviceProfile,arg2:boolean):Promise<types.DeviceProfile>;

export function SaveFanCurveProfile(arg1:string,arg2:string,arg3:Array<types.FanCurvePoint>,arg4:boolean):Promise<types.FanCurveProfile>;

export function SaveNoiseDiagnosticResult(arg1:types.NoiseDiagnosticResult):Promise<void>;

export function ScanBLEDevices(arg1:types.BLEScanParams):Promise<Array<types.BLEDeviceInfo>>;

export function ScanDeviceCandidates(arg1:string):Promise<types.DeviceScanResult>;

export function ScanWiFiDevices(arg1:string):Promise<types.WiFiDiscoveryResult>;

export function ScreenPresetThumbnail(arg1:number):Promise<string>;

export function SelectBlackSharkRgbMode(arg1:number):Promise<boolean>;

export function SendDeviceDebugCommand(arg1:string,arg2:number):Promise<types.DeviceDebugCommandResult>;

export function SetActiveDeviceProfile(arg1:string):Promise<types.DeviceProfile>;

export function SetActiveFanCurveProfile(arg1:string):Promise<void>;

export function SetAutoControl(arg1:boolean):Promise<void>;

export function SetAutoStartWithMethod(arg1:boolean,arg2:string):Promise<void>;

export function SetBlackSharkLcdDisplay(arg1:number,arg2:Array<number>):Promise<guiapp.BlackSharkLcdDisplayResult>;

export function SetBlackSharkLcdScreenEnabled(arg1:boolean):Promise<boolean>;

export function SetBlackSharkLightingEnabled(arg1:boolean):Promise<boolean>;

export function SetBlackSharkOnOffVector(arg1:boolean,arg2:boolean):Promise<boolean>;

export function SetBlackSharkRgbColorOption(arg1:number,arg2:number):Promise<boolean>;

export function SetBlackSharkRgbModeColor(arg1:number,arg2:number,arg3:boolean):Promise<boolean>;

export function SetBlackSharkRgbModeEffects(arg1:number,arg2:number,arg3:number):Promise<boolean>;

export function SetBrightness(arg1:number):Promise<boolean>;

export function SetCustomSpeed(arg1:boolean,arg2:number):Promise<void>;

export function SetDebugMode(arg1:boolean):Promise<void>;

export function SetFanCurve(arg1:Array<types.FanCurvePoint>):Promise<void>;

export function SetGearLight(arg1:boolean):Promise<boolean>;

export function SetLightStrip(arg1:types.LightStripConfig):Promise<void>;

export function SetManualGear(arg1:string,arg2:string):Promise<boolean>;

export function SetNoiseDiagnosticTarget(arg1:string,arg2:number):Promise<types.NoiseDiagnosticTargetResult>;

export function SetPowerOnStart(arg1:boolean):Promise<boolean>;

export function SetSceneRules(arg1:guiapp.SceneRulesPayload):Promise<guiapp.SceneRulesResult>;

export function SetSmartStartStop(arg1:string):Promise<boolean>;

export function SetTemperatureHistoryEnabled(arg1:boolean):Promise<void>;

export function SetTemperatureHistoryRetentionHours(arg1:number):Promise<void>;

export function SetWiFiSmartStartStopStandbySpeed(arg1:number):Promise<boolean>;

export function SetWindowsAutoStart(arg1:boolean):Promise<void>;

export function ShowWindow():Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function TestBridgeProgram():Promise<types.BridgeTemperatureData>;

export function TestDeviceProfile(arg1:types.DeviceProfileTestParams):Promise<types.DeviceProfileTestResult>;

export function TestTemperatureReading():Promise<types.TemperatureData>;

export function TransferDeviceImage(arg1:ipc.TransferDeviceImageParams):Promise<void>;

export function UpdateCompletedOnLaunch():Promise<boolean>;

export function UpdateConfig(arg1:types.AppConfig):Promise<void>;

export function UpdateGuiResponseTime():Promise<void>;

export function UploadScreenHistoryImage(arg1:string):Promise<guiapp.ScreenUploadResultPayload>;

export function UploadScreenImageFile(arg1:string,arg2:number,arg3:number,arg4:number):Promise<guiapp.ScreenUploadResultPayload>;

export function UploadScreenPreset(arg1:number):Promise<guiapp.ScreenUploadResultPayload>;

export function WindowBlurEnabled():Promise<boolean>;
